
import urllib.request
import json
import os

# URL for emoji-datasource-apple (using unpkg to get the raw json)
DATA_URL = "https://unpkg.com/emoji-datasource-apple@15.0.0/emoji.json"
OUTPUT_FILE = os.path.join(os.path.dirname(__file__), "../js/data/emojis.js")

def main():
    print(f"Downloading emoji data from {DATA_URL}...")
    try:
        with urllib.request.urlopen(DATA_URL) as response:
            data = json.loads(response.read().decode('utf-8'))
    except Exception as e:
        print(f"Error downloading data: {e}")
        return

    print("Processing emoji data...")
    
    # Category mapping to ensure consistent keys or better display names if needed
    # Keys in emoji-datasource are: "Smileys & Emotion", "People & Body", etc.
    # We will simplify them to code-friendly keys.
    category_map = {
        "Smileys & Emotion": "smileys",
        "People & Body": "people",
        "Animals & Nature": "animals",
        "Food & Drink": "food",
        "Travel & Places": "travel",
        "Activities": "activities",
        "Objects": "objects",
        "Symbols": "symbols",
        "Flags": "flags"
    }

    # Group emojis by category
    categorized_emojis = {v: [] for v in category_map.values()}
    # Also keep a general list if we encounter unknown categories, or just mapped ones?
    # Let's trust our map for now, or fallback to the original name converted to camelCase.

    keywords_dictionary = {}
    
    # Sort data by sort_order
    data.sort(key=lambda x: x.get('sort_order', 0))

    for item in data:
        # Get the actual emoji character
        # unified is hex code(s) joined by dashes. e.g. "1F600"
        codes = item['unified'].split('-')
        emoji_char = "".join([chr(int(c, 16)) for c in codes])

        cat = item.get('category')
        if not cat:
            continue
            
        # Map category
        if cat in category_map:
            key = category_map[cat]
        else:
            # simple fallback: lowercase and remove special chars
            key = cat.lower().replace('&', '').replace('  ', ' ').replace(' ', '_')
            if key not in categorized_emojis:
                categorized_emojis[key] = []
        
        categorized_emojis[key].append(emoji_char)

        # Keywords
        # item['short_name'] + item['short_names'] + item['keywords']
        kw_list = [item.get('short_name', '')] + item.get('short_names', []) + item.get('keywords', [])
        # deduplicate and join
        unique_kws = list(set([k for k in kw_list if k]))
        keywords_dictionary[emoji_char] = " ".join(unique_kws)

    # Generate JS content
    js_content = "// DESU™ emojie - Generated Emoji Data\n// Generated by scripts/update_emojis.py\n\n"
    
    js_content += "window.emojiData = {\n"
    
    # Write categories (preserving the order of the map ideally)
    
    first = True
    for cat_name, cat_key in category_map.items():
        emojis = categorized_emojis.get(cat_key, [])
        if not emojis:
            continue
            
        if not first:
            js_content += ",\n"
        first = False
        
        js_content += f"    {cat_key}: [\n"
        # Wrap lines for readabilityish
        line_buffer = "        "
        for i, emo in enumerate(emojis):
            line_buffer += f"'{emo}'"
            if i < len(emojis) - 1:
                line_buffer += ", "
            
            if len(line_buffer) > 100:
                js_content += line_buffer + "\n"
                line_buffer = "        "
        
        if line_buffer.strip():
             js_content += line_buffer + "\n"
             
        js_content += "    ]"

    js_content += "\n};\n\n"

    js_content += "window.emojiKeywords = " + json.dumps(keywords_dictionary, ensure_ascii=False, indent=4) + ";\n"
    
    print(f"Writing to {OUTPUT_FILE}...")
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(js_content)
    
    print("Done!")

if __name__ == "__main__":
    main()
